### PR TITLE
Improvements to 

### PR DESCRIPTION
**Pull request by nabrown**
Not sure if there is interest in maintaining this repo, but I'm planning to use the plugin on a boutique e-commerce site so I made a few small changes:

* add more info to README, most importantly what the options are for `placement`
* merge passed `options` with a set of defaults (previously it was either/or)
* for flyoutleft/flyoutright add `top: 0` otherwise placement is incorrect
* look for `touches` on `originalEvent`, not jQuery event (I found this in [public demo code](http://filamentgroup.github.io/enlarge/docs/), but somehow, it wasn't in repo)
* fix gruntfile so enlarge.init.js is concatted into dist/ js files
* add example of passing in options, in docs/init.js
* use a `srcset` with multiple images in the demo docs/index.html

### CODE REVIEW

**Comment by nabrown** [comment]
Sorry, if anyone is watching this repo, I just saw that the QUnit tests fail...working on it.

**Comment by toddparker** [comment]
Thanks for all your hard work on this @nabrown, we really appreciate it. We'll be taking a look at this in the next few days.

**Comment by nabrown** [comment]
Thanks @toddparker please let me know if there are any changes I should make.

**Comment by scottjehl** [comment]
I'll give these a look. We appreciate it, @nabrown  

One thing I'll need to reconcile is that we've done some work in the `updates` branch that I had to put on hold, but it has several improvements over master that hadn't made it in yet

**Pull request closed without merging**
